# -*- coding: utf-8 -*-
"""hot_days.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eSSMptPFjZNhsiEupwRItYWxrdTwMywm
"""

# ! pip install mrjob

from mrjob.job import MRJob

class Hot_Days(MRJob):

  def mapper(self, key, line):
    [station, name, state, date, snow, tmax, tmin] = line.split(',')
    if snow and float(snow) > 0:
      yield date, 1

  def reducer(self, date, snow):
    yield date, sum(snow)

if __name__ == '__main__':
  Hot_Days.run()

# ! python hot_days.py austin_weather_2017.csv



